import assert from 'node:assert/strict';
import ts from 'typescript';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
const out=new URL('../work/domain-tests/',import.meta.url);mkdirSync(out,{recursive:true});
for(const [source,name] of [['domain/model.ts','model'],['mocks/fixtures.ts','fixtures']]){let input=readFileSync(new URL('../'+source,import.meta.url),'utf8').replace("'@/domain/model'","'./model.mjs'");writeFileSync(new URL(name+'.mjs',out),ts.transpileModule(input,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
const {fixture,defaultTerms}=await import(new URL('fixtures.mjs',out));
const {sendProposal,transitionProposal,activate,contributionAction,apply,expireProposals,cancel,money}=await import(new URL('model.mjs',out));
let count=0;function test(name,fn){fn();console.log('PASS '+name);count++}
const proposal=(patch={})=>({id:'test',from:'sora',to:'nilo',payer:'sora',performer:'nilo',terms:structuredClone(defaultTerms),status:'Sent',created:new Date().toISOString(),expires:new Date(Date.now()+86400000).toISOString(),...patch});
const delivery=(author)=>({id:crypto.randomUUID(),version:1,at:new Date().toISOString(),author,notes:'Original demo test',files:[{name:'demo.wav',size:1024,type:'audio/wav'}]});
test('Paid: request → accept → payment → delivery → revision → approve',()=>{const s=fixture();sendProposal(s,proposal());assert.throws(()=>transitionProposal(s,'test','sora','Accepted'));transitionProposal(s,'test','nilo','Accepted');const c=s.collaborations.at(-1),t=c.contributions[0];assert.equal(c.status,'Awaiting payment');assert.throws(()=>contributionAction(s,c.id,t.id,'nilo','deliver',delivery('nilo')));activate(s,c.id,'sora');assert.ok(t.deadline);contributionAction(s,c.id,t.id,'nilo','deliver',delivery('nilo'));assert.throws(()=>contributionAction(s,c.id,t.id,'nilo','approve'));contributionAction(s,c.id,t.id,'sora','revise');contributionAction(s,c.id,t.id,'nilo','deliver',delivery('nilo'));assert.equal(t.deliveries[1].version,2);contributionAction(s,c.id,t.id,'sora','approve');assert.equal(c.status,'Completed');assert.throws(()=>contributionAction(s,c.id,t.id,'nilo','deliver',delivery('nilo')))});
test('Trade completes only after both reciprocal approvals',()=>{const s=fixture(),c=s.collaborations[0];const [a,b]=c.contributions;contributionAction(s,c.id,a.id,a.performer,'deliver',delivery(a.performer));contributionAction(s,c.id,a.id,a.recipient,'approve');assert.equal(c.status,'Active');contributionAction(s,c.id,b.id,b.performer,'deliver',delivery(b.performer));contributionAction(s,c.id,b.id,b.recipient,'approve');assert.equal(c.status,'Completed')});
test('Open verse reserves a candidate and creates exactly one collaboration',()=>{const s=fixture();apply(s,{id:'app',verse:'verse-0',artist:'nilo',message:'I can add a verse',price:13550,status:'Submitted'});sendProposal(s,proposal({verse:'verse-0',application:'app'}));assert.equal(s.applications[0].status,'Selected');assert.equal(s.verses[0].status,'Published');assert.throws(()=>sendProposal(s,proposal({id:'second',verse:'verse-0',application:'app'})));transitionProposal(s,'test','nilo','Accepted');assert.equal(s.verses[0].status,'Closed');assert.throws(()=>transitionProposal(s,'test','nilo','Accepted'));assert.equal(s.collaborations.filter(c=>c.proposal==='test').length,1)});
test('Invalid, wrong-person and withdrawn applications cannot be selected',()=>{const s=fixture();assert.throws(()=>sendProposal(s,proposal({verse:'verse-0',application:'missing'})));s.applications.push({id:'app',verse:'verse-0',artist:'nilo',message:'test',price:0,status:'Withdrawn'});assert.throws(()=>sendProposal(s,proposal({verse:'verse-0',application:'app'})))});
test('Expired reservation releases its candidate',()=>{const s=fixture();apply(s,{id:'app',verse:'verse-0',artist:'nilo',message:'test',price:10000,status:'Submitted'});sendProposal(s,proposal({verse:'verse-0',application:'app'}));s.proposals.at(-1).expires='2000-01-01';expireProposals(s);assert.equal(s.proposals.at(-1).status,'Expired');assert.equal(s.applications[0].status,'Submitted')});
test('Self proposals, third-party roles and missing trade deadlines are rejected',()=>{const s=fixture();assert.throws(()=>sendProposal(s,proposal({to:'sora'})));assert.throws(()=>sendProposal(s,proposal({performer:'veyra'})));assert.throws(()=>sendProposal(s,proposal({terms:{...defaultTerms,mode:'Trade'}})))});
test('Accepted agreement remains independent of public edits',()=>{const s=fixture(),p=proposal();sendProposal(s,p);transitionProposal(s,'test','nilo','Accepted');p.terms.price=999;assert.equal(s.collaborations.at(-1).agreement.price,8500);assert.throws(()=>transitionProposal(s,'test','sora','Withdrawn'))});
test('Revision cap and outsider access hold',()=>{const s=fixture(),c=s.collaborations[0],t=c.contributions[0];c.agreement.revisions=0;contributionAction(s,c.id,t.id,t.performer,'deliver',delivery(t.performer));assert.throws(()=>contributionAction(s,c.id,t.id,'veyra','approve'));assert.throws(()=>contributionAction(s,c.id,t.id,t.recipient,'revise'))});
test('Cancellation requires both participants after activation',()=>{const s=fixture(),c=s.collaborations[0];cancel(s,c.id,'sora');assert.equal(c.status,'Active');cancel(s,c.id,'nilo');assert.equal(c.status,'Cancelled')});
test('Cent amounts remain exact in display',()=>assert.equal(money(8550),'€85.50'));
console.log(`${count} domain scenarios passed.`);
