export type Mode='Paid'|'Trade';
export type Artist={id:string;slug:string;name:string;genre:string;language:string;bio:string;art:number;price:number;days:number;trade:boolean;demo:boolean};
export type Offer={id:string;artist:string;title:string;mode:Mode;price:number;days:number;revisions:number;files:string;archived:boolean};
export type Verse={id:string;owner:string;title:string;brief:string;genre:string;language:string;mode:Mode;budget:number;bpm:number;key:string;art:number;status:'Draft'|'Published'|'Closed'};
export type Application={id:string;verse:string;artist:string;message:string;price:number;status:'Submitted'|'Shortlisted'|'Selected'|'Rejected'|'Withdrawn'};
export type Terms={title:string;brief:string;mode:Mode;price:number;days:number;revisions:number;files:string;yourContribution:string;theirContribution:string;credits:string;rights:string;promotion:string;demoName?:string;tradeDate?:string;theirTradeDate?:string};
export type Proposal={id:string;from:string;to:string;payer:string;performer:string;verse?:string;application?:string;terms:Terms;status:'Draft'|'Sent'|'Accepted'|'Declined'|'Withdrawn'|'Expired';created:string;expires:string};
export type Delivery={id:string;version:number;at:string;author:string;notes:string;files:{name:string;size:number;url?:string;type:string}[]};
export type Contribution={id:string;performer:string;recipient:string;obligation:string;status:'Pending'|'Delivered'|'Revision requested'|'Approved';revisions:number;deadline?:string;deliveries:Delivery[]};
export type Collaboration={id:string;proposal:string;participants:string[];payer:string;agreement:Terms;accepted:string;status:'Awaiting payment'|'Active'|'Completed'|'Cancelled';cancelBy?:string;contributions:Contribution[]};
export type Message={id:string;proposal:string;author:string;text:string;at:string};
export type Store={version:1;artists:Artist[];offers:Offer[];verses:Verse[];applications:Application[];proposals:Proposal[];collaborations:Collaboration[];messages:Message[];blocked:string[];reports:{target:string;reason:string;author:string}[];reviews:{collaboration:string;author:string;rating:number;text:string}[]};
export const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
export const money=(n:number)=>new Intl.NumberFormat('en',{style:'currency',currency:'EUR',minimumFractionDigits:n%100?2:0,maximumFractionDigits:2}).format(n/100);
const check=(ok:unknown,msg:string)=>{if(!ok)throw new Error(msg)};
export function sendProposal(s:Store,p:Proposal){expireProposals(s);check(p.from!==p.to,'You cannot propose to yourself.');check(s.artists.some(a=>a.id===p.from)&&s.artists.some(a=>a.id===p.to),'Unknown participant.');check(p.payer===p.from&&p.performer===p.to,'Contribution roles must match the participants.');check(Number.isInteger(p.terms.revisions)&&p.terms.revisions>=0&&p.terms.revisions<=10,'Invalid revision allowance.');if(p.terms.mode==='Trade'){check(Date.parse(p.terms.tradeDate||'')>Date.now()&&Date.parse(p.terms.theirTradeDate||p.terms.tradeDate||'')>Date.now(),'Set a future deadline for both contributions.');p.terms.price=0;}check(!s.blocked.includes(p.to)&&!s.blocked.includes(p.from),'New interactions with this artist are blocked.');check(p.terms.price>=0&&Number.isInteger(p.terms.price),'Invalid price.');check(p.terms.days>=1&&p.terms.days<=90,'Choose 1–90 days.');check(p.terms.brief.trim()&&p.terms.theirContribution.trim(),'Add a brief and contribution.');if(p.terms.mode==='Trade')check(p.terms.yourContribution.trim(),'Describe both contributions.');if(p.verse){const v=s.verses.find(v=>v.id===p.verse);check(v?.status==='Published'&&v.owner===p.from,'Open verse is unavailable.');check(v?.mode===p.terms.mode,'Collaboration type must match the announcement.');const app=s.applications.find(a=>a.id===p.application);check(app&&app.verse===p.verse&&app.artist===p.to&&['Submitted','Shortlisted'].includes(app.status),'Choose an eligible application for this announcement.');check(!s.proposals.some(x=>x.verse===p.verse&&x.status==='Sent'&&Date.parse(x.expires)>Date.now()),'A final proposal is already pending.');}if(p.application)s.applications.find(a=>a.id===p.application)!.status='Selected';s.proposals.push(p);}
export function transitionProposal(s:Store,id:string,actor:string,action:'Accepted'|'Declined'|'Withdrawn'){
 const p=s.proposals.find(p=>p.id===id);check(p,'Proposal not found.');if(!p)return;check(p.status==='Sent','This proposal is no longer pending.');check(Date.parse(p.expires)>Date.now(),'This proposal has expired.');check(action==='Withdrawn'?p.from===actor:p.to===actor,'Only the permitted participant can do this.');
 if(action==='Accepted'){if(p.application){const a=s.applications.find(a=>a.id===p.application);check(a?.status==='Selected'&&a.verse===p.verse&&a.artist===p.to,'This candidate is no longer reserved.');}
 check(!s.collaborations.some(c=>c.proposal===id),'Already accepted.');if(p.verse){const v=s.verses.find(v=>v.id===p.verse);check(v?.status==='Published'&&!s.collaborations.some(c=>s.proposals.find(x=>x.id===c.proposal)?.verse===p.verse),'This open verse already has a collaborator.');if(v)v.status='Closed';s.applications.filter(a=>a.verse===p.verse).forEach(a=>a.status=a.id===p.application?'Selected':'Rejected');}
 const now=new Date().toISOString();const contributions:Contribution[]=[{id:uid(),performer:p.performer,recipient:p.payer,obligation:p.terms.theirContribution,status:'Pending',revisions:0,deliveries:[],deadline:p.terms.mode==='Trade'?(p.terms.theirTradeDate||p.terms.tradeDate):undefined}];if(p.terms.mode==='Trade')contributions.push({id:uid(),performer:p.payer,recipient:p.performer,obligation:p.terms.yourContribution,status:'Pending',revisions:0,deliveries:[],deadline:p.terms.tradeDate});
 s.collaborations.push({id:uid(),proposal:id,participants:[p.from,p.to],payer:p.payer,agreement:structuredClone(p.terms),accepted:now,status:p.terms.mode==='Paid'?'Awaiting payment':'Active',contributions});
 }else if(p.application){const a=s.applications.find(a=>a.id===p.application);if(a)a.status='Submitted';}p.status=action;
}
export function activate(s:Store,id:string,actor:string){const c=s.collaborations.find(c=>c.id===id);check(c&&c.payer===actor&&c.status==='Awaiting payment','Only the payer can simulate this payment.');if(c){c.status='Active';c.contributions.forEach(t=>t.deadline=new Date(Date.now()+c.agreement.days*86400000).toISOString());}}
export function contributionAction(s:Store,id:string,tid:string,actor:string,action:'deliver'|'approve'|'revise',delivery?:Delivery){const c=s.collaborations.find(c=>c.id===id);check(c?.status==='Active','This collaboration is not active.');const t=c?.contributions.find(t=>t.id===tid);check(t,'Contribution not found.');if(!t||!c)return;if(action==='deliver'){check(t.performer===actor&&['Pending','Revision requested'].includes(t.status),'You cannot upload to this contribution.');check(delivery&&delivery.files.length>0,'Attach at least one audio or ZIP file.');t.deliveries.push({...delivery!,version:t.deliveries.length+1});t.status='Delivered';}else{check(t.recipient===actor&&t.status==='Delivered','Only the recipient can review a delivery.');if(action==='revise'){check(t.revisions<c.agreement.revisions,'No included revisions remain.');t.revisions++;t.status='Revision requested';}else t.status='Approved';}if(c.contributions.every(t=>t.status==='Approved'))c.status='Completed';}
export function cancel(s:Store,id:string,actor:string){const c=s.collaborations.find(c=>c.id===id);check(c?.participants.includes(actor),'Access denied.');if(!c)return;check(c.status==='Awaiting payment'||c.status==='Active','This work cannot be cancelled.');if(c.status==='Awaiting payment'){check(c.payer===actor,'Only the payer can cancel before activation.');c.status='Cancelled';}else if(c.cancelBy&&c.cancelBy!==actor)c.status='Cancelled';else c.cancelBy=actor;}
export function apply(s:Store,a:Application){const v=s.verses.find(v=>v.id===a.verse);check(v?.status==='Published'&&v.owner!==a.artist,'This announcement is not open to your application.');check(s.artists.find(x=>x.id===a.artist)?.demo,'Add a demo to your profile first.');check(!s.blocked.includes(v!.owner),'This artist is blocked.');check(!s.applications.some(x=>x.verse===a.verse&&x.artist===a.artist&&x.status!=='Withdrawn'),'You already have an active application.');s.applications=s.applications.filter(x=>!(x.verse===a.verse&&x.artist===a.artist));s.applications.push(a);}

export function expireProposals(s:Store){for(const p of s.proposals){if(p.status==='Sent'&&Date.parse(p.expires)<=Date.now()){p.status='Expired';if(p.application){const a=s.applications.find(a=>a.id===p.application);if(a?.status==='Selected')a.status='Submitted';}}}}
