'use client';
import {createContext,useContext,useRef,useState,ReactNode} from 'react';
import {Play,Pause,SkipBack,SkipForward,Volume2,Disc3,ChevronUp} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {toast} from 'sonner';
export type Track={id:string;title:string;artist:string;art:number;url:string;private?:boolean};
const Context=createContext<{play:(t:Track)=>void;track:Track|null;playing:boolean;clear:()=>void}>({play:()=>{},track:null,playing:false,clear:()=>{}});
export const usePlayer=()=>useContext(Context);
export function Artwork({art,className=''}:{art:number;className?:string}){return <div role="img" aria-label="Original demo cover artwork" className={`cover ${className}`} style={{backgroundImage:'url(/artwork.png)',backgroundSize:'300% 300%',backgroundPosition:`${art%3*50}% ${Math.floor(art/3)*50}%`}}/>}
const time=(s:number)=>`${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,'0')}`;
export function PlayerProvider({children}:{children:ReactNode}){const audio=useRef<HTMLAudioElement>(null);const [track,setTrack]=useState<Track|null>(null),[playing,setPlaying]=useState(false),[pos,setPos]=useState(0),[duration,setDuration]=useState(0),[expanded,setExpanded]=useState(false);function play(t:Track){const a=audio.current;if(!a)return;if(t.id===track?.id){if(a.paused)a.play().catch(()=>toast.error('Audio could not play. Try again.'));else a.pause();return;}a.pause();setPlaying(false);setTrack(t);setPos(0);setDuration(0);a.src=t.url;a.load();a.play().catch(()=>{setPlaying(false);toast.error('Audio unavailable. Try another demo.');});}function clear(){if(audio.current){audio.current.pause();audio.current.removeAttribute('src');audio.current.load();}setTrack(null);setPlaying(false);setPos(0);setDuration(0)}return <Context.Provider value={{play,track,playing,clear}}>{children}<audio ref={audio} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={()=>setPos(audio.current?.currentTime||0)} onLoadedMetadata={()=>setDuration(audio.current?.duration||0)} onError={()=>{setPlaying(false);if(track)toast.error('The audio file is unavailable. Select another track.');}}/><footer className={`player ${expanded?'expanded':''}`}><div className="now-playing">{track?<Artwork art={track.art}/>:<Disc3 size={36}/>}<div><b>{track?.title||'A new sound is waiting'}</b><p>{track?.artist||'Select a demo to start listening'}</p></div></div><div className="playback"><div className="transport"><button aria-label="Restart track" disabled={!track} onClick={()=>{if(audio.current)audio.current.currentTime=0}}><SkipBack size={17}/></button><button className="play-main" aria-label={playing?'Pause':'Play'} disabled={!track} onClick={()=>track&&play(track)}>{playing?<Pause size={17} fill="currentColor"/>:<Play size={17} fill="currentColor"/>}</button><button aria-label="Skip forward 10 seconds" disabled={!track} onClick={()=>{if(audio.current)audio.current.currentTime=Math.min(duration,pos+10)}}><SkipForward size={17}/></button></div><div className="seek"><small>{time(pos)}</small><Slider aria-label="Track position" value={[pos]} max={duration||1} step={.1} disabled={!duration} onValueChange={v=>{if(audio.current)audio.current.currentTime=v[0]}}/><small>{time(duration)}</small></div></div><div className="volume"><Volume2 size={17}/><Slider aria-label="Volume" defaultValue={[.7]} max={1} step={.01} onValueChange={v=>{if(audio.current)audio.current.volume=v[0]}}/><span className="badge">Demo audio</span></div><button className="expand-player" aria-label="Expand audio controls" onClick={()=>setExpanded(!expanded)}><ChevronUp size={20}/></button></footer></Context.Provider>}
